id: funneldrop_install_git
hints:
- Gooogle "git scm download"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "Hey ninja how are ya? ready for anotyher one?"
        delay: 2000
      - text: "Now let's install git - please install it and when you're done open a terminal and run 'git --version' and paste the output here"
      delay: 3500
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - "git version"
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: you're killing it!
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: I didn't get that... if you run into issues - please ask team members for advice!
              delay: 2500