id: install_nvm
hints:
- "You can use: https://tecadmin.net/install-nvm-macos-with-homebrew/"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hey Bruce Lee, I see you're on s streak :) ready for another one?"
        delay: 2000
      - text: "Now let's install nvm - when you're done open a terminal and run `nvm -h` and paste the first line of the output here"
      delay: 3500
trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings: 
          - "Node Version Manager"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: you're da man, or da woman, or whatever pronoun you want... shit this stuff is difficult for a bot like me...
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: I didn't get that... if you run into issues - please ask team members for advice!
              delay: 2500