id: funneldrop_install_typescript
hints:
- "Run: `sudo npm install -g typescript`"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "Very nice indeed!"
        delay: 2000
      - text: "Now it's time to install typescript - please type 'done' when you're finished"
      delay: 3500
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - done
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: new level of awesomeness has been unlocked - way to go!
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: I didn't get that... if you run into issues - please ask team members for advice!
              delay: 2500